# Generated by Django 5.2.8 on 2026-01-02 10:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdetails_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
