# Generated by Django 5.2.8 on 2026-01-02 10:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venders', '0009_multivenders_agreement_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='food_image'),
        ),
        migrations.AlterField(
            model_name='multivenders',
            name='restaurent_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='restaurant_image'),
        ),
        migrations.AlterField(
            model_name='multivenders',
            name='restaurent_lic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='restaurant_license'),
        ),
    ]
